### ISSUE TITLE
Timer always pausing

### ISSUE THREAD

**Issue by bickhorn** [nymanjens/quizmaster#10]
Hello, 

I've tried a quiz with 10 people and at the first question the timer paused.

When pressing spacebar it started again, but pause quickly again. 
Restarting the Docker image didn't work. I tried different browser. 

Do you have an idea of what happen and how to proceed to stop this ?

**Comment by nymanjens** [comment]
I don't think I've seen issues with the timer pausing yet.

The timer should pause when everyone has given their answer, but I guess that's not the issue here, right?

The only other thing I can think of is if your quiz-config.yaml has some feature enabled that will pause the timer everytime a contestant presses a button. Can you maybe share the config of this first question?

**Comment by bickhorn** [comment]
And it doesnt not only pause the first question, but all the questions of every round :'( 

Here is my quiz-config.yaml and the first question:
```
title: Quiz
author: "Connectez-vous sur http://XXXXXXX"
instructionsOnFirstSlide: Bon courage 
masterSecret: MyPassword # Remove this line to allow anyone to access the master controls
language: en # This is the default. The other supported languages can be found in application.conf

usageStatistics:
    sendAnonymousUsageDataAtEndOfQuiz: false
# Optional - Define custom defaults
defaults:
  maxTimeSeconds: 30
  pointsToGain: 1
  multipleAnswers_pointsToGainPerAnswer: 1
  multipleQuestions_pointsToGainPerQuestion: 1
  orderItems_pointsToGainInTotal: 1

rounds:
    - name: PC
      questions:

            # Special question type: Provide multiple answers
            - questionType: multipleAnswers
              question: Parmi ces photos, seulement 3 représentent des préformes, lesquelles ?
              answers:
                - { answer: "A", answerDetail: "Préforme du siège"}
                - { answer: "B", answerDetail: "Préforme  forte épaisseur" }
                - { answer: "D", answerDetail: "Préforme en Z" }
              answersHaveToBeInSameOrder: false
              image: PC/question1.png
              answerImage: PC/reponse1.png
```
