### ISSUE TITLE
Wiki for `config.yaml` | added option `answerIndex`

### ISSUE THREAD

**Issue by ExtremOPS** [nymanjens/quizmaster#17]
Hi there,

first of all: thank you, @nymanjens, very much for this project. It is really cool.

I was wondering if there is somewhere a documentation about the possible options in the [`quiz-config.yml`](https://github.com/nymanjens/quizmaster/blob/master/conf/quiz/quiz-config.yml). Especially I would be highly interested int the option to define the answer by the index instead of re-writing it. 

E.g., instead of this
```yaml
      # Standard multiple-choice question
      - question: What is the capital of Belgium?
        choices: [Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua., Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat., Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur., Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.]
        answer: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        pointsToGain: 1
        pointsToGainOnFirstAnswer: 2 # Double points for first right answer
``` 

maybe something like this

```yaml
      # Standard multiple-choice question
      - question: What is the capital of Belgium?
        choices: [Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua., Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat., Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur., Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.]
        answerIndex: 4
        pointsToGain: 1
        pointsToGainOnFirstAnswer: 2 # Double points for first right answer
``` 

I am not profound enough in Scala that I could do it myself....

**Comment by nymanjens** [comment]
> I was wondering if there is somewhere a documentation about the possible options in the [quiz-config.yml](https://github.com/nymanjens/quizmaster/blob/master/conf/quiz/quiz-config.yml).

The demo config file you linked is supposed to explain all possible things you can do. Is there anything missing or config option that you'd like to see explained further?

> Especially I would be highly interested int the option to define the answer by the index instead of re-writing it.

I try to avoid having multiple ways to do the same thing because it adds complexity for people who try to learn the configuration schema. When comparing `answerIndex` to `answer`, the former is a lot shorter, but I'd be worried that it could accidentally lead to the wrong answer being selected.

**Comment by ExtremOPS** [comment]
Hi there,

thank you for replying. 

> The demo config file you linked is supposed to explain all possible things you can do. Is there anything missing or config option that you'd like to see explained further?

No, I think it is all fine. I was just wondering if my requested option is a valid option. 

> I try to avoid having multiple ways to do the same thing because it adds complexity for people who try to learn the configuration schema. When comparing answerIndex to answer, the former is a lot shorter, but I'd be worried that it could accidentally lead to the wrong answer being selected.

Yes, that is also true! Especially if it would be something like

```yaml
      # Standard multiple-choice question
      - question: First integer greater than 0?
        choices: [4, 3, 42, 1]
        answerIndex: 4
        pointsToGain: 1
```

As said, there are for sure certain applications where it would make it easier but in the end it is your project and your decision :-)

Anyways, thank you very much for answering!!!!
